exclude = [
    'http://localhost:.*',
    'http://127.0.0.1:.*',
    'http://10.93.26.193:.*',
    'https://lamba-23.github.io/LAMBA/.*',
    'https://github.com/LAMBA-23/LAMBA/releases/download/v0.1.0/app-debug.apk',
    'https://github.com/LAMBA-23/LAMBA/releases/download/.*',
    'https://github.com/LAMBA-23/LAMBA/issues/new\\?template=.*'
]
