exclude = [
    'http://localhost:.*',
    'http://127.0.0.1:.*',
    'http://10.93.26.193:.*',
    'https://github.com/orgs/LAMBA-23/projects/1/views/1',
    'https://github.com/orgs/LAMBA-23/projects/1/views/3'
]
